<?php

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * {@inheritdoc}
 */
function elog_core_entity_presave(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node' && $entity->getType() == 'logentry') {
    $ls = Drupal::service('log_number.service');
    $log_number = $ls->nextLogNumber();
    if ($entity->isNew()){
      if (! $entity->field_lognumber->isEmpty()) {
        //var_dump(get_class($entity->field_lognumber));
        if ($entity->field_lognumber->first()){
          $submitted = $entity->field_lognumber->first()->value;
          if ($submitted < 1) {
            $entity->set('field_lognumber', $log_number);
          }
        }
      }
    }else{
      //TODO force back to original as safegaurd against nefarious submit

    }


  }
}
